"""Initial Schema

Revision ID: 50b03c753e4c
Revises: 
Create Date: 2025-12-27 22:23:51.983800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '50b03c753e4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', mysql.VARCHAR(collation='utf8mb4_0900_ai_ci', length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_0900_ai_ci', length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('total_earning', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_name', mysql.VARCHAR(collation='utf8mb4_0900_ai_ci', length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cat_id'),
    sa.UniqueConstraint('user_id', 'category_name', name='uq_user_category')
    )
    op.create_index(op.f('ix_Categories_user_id'), 'Categories', ['user_id'], unique=False)
    op.create_table('Expenses',
    sa.Column('exp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=450), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['Categories.cat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exp_id')
    )
    op.create_index(op.f('ix_Expenses_cat_id'), 'Expenses', ['cat_id'], unique=False)
    op.create_index(op.f('ix_Expenses_user_id'), 'Expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Expenses_user_id'), table_name='Expenses')
    op.drop_index(op.f('ix_Expenses_cat_id'), table_name='Expenses')
    op.drop_table('Expenses')
    op.drop_index(op.f('ix_Categories_user_id'), table_name='Categories')
    op.drop_table('Categories')
    op.drop_table('Users')
    # ### end Alembic commands ###
